--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-03-13 20:11:12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 24887)
-- Name: review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review (
    id bigint NOT NULL,
    book_id character varying(255) NOT NULL,
    comment character varying(255),
    rate integer NOT NULL,
    review_date timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL
);


ALTER TABLE public.review OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 24886)
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4843 (class 0 OID 24887)
-- Dependencies: 218
-- Data for Name: review; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.review (id, book_id, comment, rate, review_date, user_id) FROM stdin;
1	isbn	Review 1	5	2025-03-08 09:53:41.446511	azerty
2	isbn	Review from azerty again	5	2025-03-08 09:54:39.381748	azerty
3	isbn2	Review from azerty again	5	2025-03-08 10:00:30.340415	azerty
\.


--
-- TOC entry 4849 (class 0 OID 0)
-- Dependencies: 217
-- Name: review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.review_id_seq', 3, true);


--
-- TOC entry 4696 (class 2606 OID 24893)
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


-- Completed on 2025-03-13 20:11:12

--
-- PostgreSQL database dump complete
--

