---------------------------------
-- Database configuration (H2)
---------------------------------

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id VARCHAR(255) NOT NULL,
    comment VARCHAR(255),
    rate INT NOT NULL,
    review_date TIMESTAMP NOT NULL,
    user_id VARCHAR(255) NOT NULL
);

